@echo off
chcp 65001 >nul
cd /d "C:\Users\yoshitaka\daily-ai-news"

echo 🔧 CSS参照修正 - style.cssへの参照を修正中...

echo 📝 ファイルを追加...
git add index.html style.css

echo 💾 コミット中...
git commit -m "fix: Correct CSS reference from style_enhanced_ranking.css to style.css

- Fixed CSS link in index.html to reference style.css
- This will resolve styling issues on GitHub Pages
- style.css is the correct file generated by build process

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"

echo 📤 GitHubに強制プッシュ中...
git push --force origin main

echo ✅ CSS修正版がプッシュ完了！
echo 🔄 GitHub Actionsが自動で開始されます (~30秒後)
echo 🌐 サイト確認: https://awano27.github.io/daily-ai-news-pages/
echo ⏱️ 完了予定: 2-5分後
echo 📋 期待される修正:
echo   - CSSスタイリングが正常に適用
echo   - style.css が正しく読み込まれる
echo   - サイトのレイアウトとデザインが復旧
echo   - タブ機能も引き続き正常動作

pause